== 11969 Message Class Generation

=== 1 Abstract

When connecting an xtUML-generated application to a browser-based client it is often necessary to 
produce a Java class for each interface message passed between the application and a client.
This feature enables a user to specify, via marking, interface messages for which a Java class must
be generated.  

=== 2 Introduction and Background

Some web frameworks, such as Spring, require a Java class for each message.  The Spring framework 
requires each message class to define 'get' and 'set' methods for each attribute.  Manually writing
such classes is tedious and error-prone, so this feature automates the process.

Refer to the hand-coded message classes within the 
https://github.com/johnrwolfe/CarPark/tree/master/Deployment/src/main/java/deployment[CarPark Deployment project] 
for examples.

Note: the requirements, below, are specific to the Spring framework. Other frameworks may differ in 
name formatting, constructor parameters, etc.

=== 3 Requirements

. A mark specifies for which messages a Java class must be generated.
. Each generated message class includes a `messageName` data member of type String.
. Each message parameter is represented by a corresponding data member of type String.
. Each data member name is formatted as `camelCase` with a lowercase initial letter.
. A 'get' accessor is generated for each data member.
. A 'set' accessor is generated for each data member.
. Each 'get'/'set' accessor name is formatted as `camelCase` with a lowercase initial letter.
For example, the accessor names for a data member named `ticketNumber` are:
** `getTicketNumber`
** `setTicketNumber` 

=== 4 Analysis

Marking is applied on an interface boundary, and a class is generated for each
message of a marked interface.  

For each marked interface, a package is created as a peer to the generated Java interface 
representing the xtUML interface.  Message classes for the marked interface are placed 
within this package, preventing collisions between identically named message classes 
generated from different xtUML interface definitions which happen to contain identically
named messages.  

=== 5 Design

* Add a mark named `GenerateMessageClasses` to be applied to an interface definition.  This 
mark accepts as parameters the name of the interface definition and the path (including the
project name) to it.

* Develop templates for generation of a Java class corresponding to a message.
* At Interface.render(), when marked: for each related (R419) message apply the templates to emit a Java class file.
* Use the Interface file path and package name as bases for emitting to a child package of the interface package.

=== 6 Work required

=== 7 Implementation Comments

Branch https://github.com/amullarney/ciera/tree/Ciera11969_exploratory is an early prototype of message class generation. +
It marks a Port rather than an Interface, generating classes into the Port implementation package - which is less appropriate. +

=== 8 Acceptance Test

The Payroll application should be built with suggested markings and tested with browser clients.

=== 9 User Documentation

Describe the end user documentation that was added for this change.

=== 10 Code Changes

- fork/repository: https://github.com/amullarney/ciera
- branch: https://github.com/amullarney/ciera/tree/Ciera11969_exploratory

----
 Put the file list here
----

=== 11 Document References

In this section, list all the documents that the reader may need to refer to.
Give the full path to reference a file.

. [[dr-1]] https://support.onefact.net/issues/11969

