== MASL loader analysis

=== 1 Abstract

This note examines the completeness of an existing MASL model and loader as well as
the work required to integrate into a Ciera-based model based model compiler
project.

=== 2 Introduction and Background

This analysis is done in the context of the Jay project <<dr-1>> <<dr-2>>
<<dr-3>>

A model of the MASL language (OOA of MASL) has been created along with a
parser/loader (Stratus). That model will be the primary basis of this analysis.
<<dr-4>> <<dr-5>> <<dr-6>> <<dr-7>>

=== 3 Requirements

3.1 Analyze the completeness of the MASL model (`ooamasl`)

3.2 Analyze the completeness of the loader (`stratus`)

3.3 Determine the work required to integrate with a Ciera-based model compiler

=== 4 Analysis

4.1 OOA of MASL

The OOA of MASL is more or less derived directly from the parse grammar used by
the existing C++ MASL code generator. As such, there is high confidence that
it contains all necessary structures to represent the MASL language fully
enough for translation. There are a few opportunities for improvment, some of
which are pointed out in section 5.3 of the Stratus implementation note. These
improvements are not considered necessary for the requirements of this project
however, so any work done in this area will be considered opportunistically but
prioritized below the actual project requirements.

4.2 Stratus

The Stratus MASL parser/loader has been tested with a large suite of MASL
models (however admittedly the suite is light on MASL action language bodies).
It works well in all the test cases. A proof of concept has been created that
integrates the Stratus loader with a Ciera based model compiler, loads a MASL
model, and produces compilable Ciera/Java output.

There are several "TODO"s left in the Stratus loader code which should be considered:

. Min and max values for builtins
. Overloading services not [well] supported
. Bogus relationship specs get created if can't be resolved
  - nav to associator class not supported
. Objects need to be pre-declared otherwise problems occur (probably OK as a limitation)
. Multiple stream operators not supported
. Cannot distinguision between instance and instance set types in action language selections
. Call expression can't determine which type of service for subtype
. Implicit loop variables
. Nested code blocks not supported
. Type of binary expression assumed to be the type of the LHS expression
. Reverse semantics for ordered by selections not well understood
  - reverse at top level selection _and_ at each field specification?
. Attribute name expression problems
. Various type related issues
  - slice expressions
  - literal integers
  - literal characters
  - literal strings
  - literal timestamps
  - literal durations
  - literal null
  - literal flush

4.3 Integration with Ciera-based model compiler

A proof of concept has been created which integrates OOA of MASL, Stratus, and
Ciera architecture together into one model compiler project.  There is a good
deal of adjusting that needs to be done to make it sustainable however.

4.3.1 Completely separate the core architecutre model from the xtUML/OAL
translation logic

This cannot be reused for the MASL version of Ciera and represents dead wait to
parse/translate if included. Additionally this exercise will better define the
target architecture for reuse and will improve performance of the build of the
SQL loader compiler and the template compiler. This will probably be made into
its own separate xtUML project.

4.3.2 Completely separate the core architecture model from the OOA of OOA

There are a few spanning relationships between the OOA of OOA and the Ciera
architecture model. These are used to make 1-to-1 relationships between source
artifacts and their target counterparts. This is convenient for any type of
multi-pass generation. At the moment the relationships are conditional on the
OOA of OOA side which allows the OOA of OOA to be independent of the Ciera
architecture. These relationships must be changed to be conditional on _both_
sides so that the Ciera model can be populated from a different source model
(e.g. OOA of MASL). Additionally, the relationships should be defined in
packages that reside in the same project with the translation functions since
these relationships "belong" to the translation between xtUML and Ciera
architecture and are not part of the core architecture itself. Without doing
this, any other model translations will be implicitly dependent on the OOA of
OOA.

4.3.3 Migrate from ANTLR 3 to ANTLR 4 for the Stratus loader

The stratus loader is based on ANTLR 3.5.2. The Ciera model compilers use the
latest major version of ANTLR for templates and for SQL loading. Upgrading to
v4 for the Stratus loader would avoid needing to include two different versions
of the ANTLR runtime in the project.

4.3.4 Resolve class key letter collisions

There are a handful of name collisions within the Ciera architecture model and
the OOA of MASL. They are listed below:

Class key letters:

- Expression
- UserDefinedType
- CodeBlock
- State
- Statement
- FunctionInvocation

Enumerated Types

- Multiplicity
- TransitionType
- Visibility

These need to be either manually renamed or moved to a shared location.

=== 5 Work required

The following issues have been raised as part of the Jay project to track the
large independent projects identified in the analysis. Miscellaneous items not
covered by one of the following issues will be tracked as part of the parent
task #12102 <<dr-8>>

5.1 Completely separate the core architecutre model from the xtUML/OAL <<dr-9>>

5.2 Completely separate the core architecture model from the OOA of OOA <<dr-10>>

5.3 Migrate from ANTLR 3 to ANTLR 4 for the Stratus loader <<dr-11>>

5.4 Resolve class key letter collisions <<dr-12>>

=== 6 Document References

. [[dr-1]] https://support.onefact.net/issues/12094[Support MASL translation (project jay)]
. [[dr-2]] https://github.com/xtuml/ciera/wiki/12094_support_masl[Initial project analysis]
. [[dr-3]] https://docs.google.com/document/d/1o2FmFKkuxJRxYEzXfX4qE7Do72EkdSlKgjC3rxirmOg/edit#heading=h.x1vg2cgahpkg[Jay SOW]
. [[dr-4]] https://support.onefact.net/issues/11745[Parse MASL into xtUML meta-model of MASL activity (analysis)]
. [[dr-5]] https://github.com/xtuml/mc/tree/master/doc/notes/11745_loadmasl[Stratus engineering notes]
. [[dr-6]] https://github.com/xtuml/mc/tree/master/model/ooamasl[OOA of MASL model]
. [[dr-7]] https://github.com/xtuml/mc/tree/master/model/stratus[Stratus model]
. [[dr-8]] https://support.onefact.net/issues/12102[Project jay: Instance loading using Stratus integrated]
. [[dr-9]] https://support.onefact.net/issues/12264[Completely separate the core architecutre model from the xtUML/OAL]
. [[dr-10]] https://support.onefact.net/issues/12265[Completely separate the core architecture model from the OOA of OOA]
. [[dr-11]] https://support.onefact.net/issues/12262[Migrate from ANTLR 3 to ANTLR 4 for the Stratus loader]
. [[dr-12]] https://support.onefact.net/issues/12263[Resolve class key letter collisions]
