== Title goes here

NOTE: Each section has a description that states the purpose of that section.
Delete these section descriptions before checking in your note. Delete this
note as well.

=== 1 Abstract

In this section, give a summary of the design that this note aims to describe.

TIP: This document is marked down with http://asciidoc.org/[AsciiDoc]. You can
get tips from the
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Quick
Reference].

=== 2 Introduction and Background

In this section, outline the important points relating to this issue/bug that
the reader would need to know in order to understand the rest of this document.
Here is an example reference to a document reference <<dr-3>>. Here is an
example with named text <<dr-3,SMASL Specification>>.

=== 3 Requirements

This section
describes the requirements that need to be satisfied.
Each requirement should be as short and simple
as possible and must be clearly defined.

 Here is some text that is not formatted and line-wrapped. Do this by simply
 prepending a blank to the beginning of each line.

Here we reference a section heading below, like <<3.2.1 Example sub-item>>.

==== 3.1 Item
===== 3.1.1 Example sub-item
Paragraphs can start here.

* example bulleted list item
  - Example Sub list item with example named document reference <<dr-2,Analyze
    Options for Migration>>

==== 3.2 Section
===== 3.2.1 Example sub-section

1. First Example Numbered List Element
2. Second
  a. enumerated sub first
  b. enumerated sub second
3. third

=== 4 Analysis

This section sets out a brief analysis of the problem to be resolved.

=== 5 Design

In this section, describe in detail each section of the analysis, how the task
will be accomplished, what technologies will be used, algorithms, etc.

=== 6 Work required

Elaborate on each point of the design describe how you implemented each step.
This section breaks out the consequential work (as a numbered list) needed to
meet the requirements specified in the Requirements section.

=== 7 Implementation Comments

If the design cannot be implemented as written or if it needs some
modification, enumerate the changes to the design in this section. If there
was no preceding design note, then this section documents any deviations from
the implementation as presented at the pre-implementation engineering review.

.Recommended Type Mapping
[options="header"]
|===
| MASL type  | xtUML type recommendation
| boolean    | Use native `boolean`
| byte       | Create UDT with core type `integer`
| character  | Create UDT with core type `integer`
|===

==== 7.1 Item 1

[source,java]
----
    // java code example
    public void clearDatabase(IProgressMonitor pm)
    {
        // clear the corresponding graphics-root's database
        OoaofgraphicsUtil.clearGraphicsDatabase(rootId, pm);

        Ooaofooa.getDefaultInstance().fireModelElementUnloaded(this);
    }
----

===== 7.1.1 Example sub-item

=== 8 Acceptance Test

Outline all the tests that need to pass and describe the method that you
will use to design and perform the tests.

. Here is another ordered list element allowing the renderer to do the work.
  This may be better for unit test steps that do not get explicitly referenced.
. second one
  .. enumerated sub first
  .. enumerated sub second
. third

=== 9 User Documentation

Describe the end user documentation that was added for this change.

=== 10 Code Changes

- fork/repository: your_fork/repo_name
- branch: your_branch_name_here

----
 Put the file list here
----

=== 11 Document References

In this section, list all the documents that the reader may need to refer to.
Give the full path to reference a file.

. [[dr-1]] https://support.onefact.net/issues/NNNNN[NNNNN - headline]
. [[dr-2]] ...
. [[dr-3]] link:../8073_masl_parser/8277_serial_masl_spec.md[Serial MASL (SMASL) Specification]
